name: flutter_chat_demo
description: This is the demo for chat app by Flutter

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 0.1.2
  firebase_auth: ^0.11.1+5
  google_sign_in: 4.0.1+1
  cloud_firestore: 0.11.0+2
  image_picker: 0.5.0+9
  shared_preferences: 0.5.1+2
  firebase_storage: ^3.0.0
  cached_network_image: 0.8.0
  intl: 0.15.8
  youtube_player_flutter: ^1.1.0
  country_pickers: ^1.0.2
  firebase_database: ^3.0.2
  fluttertoast: ^3.0.3
  flutter_calendar_carousel: ^1.3.17
  date_utils: ^0.1.0+2
  table_calendar: ^1.2.0
  flutter_calendar: ^0.0.8
  stripe_payment: ^0.1.0
  marquee: ^1.3.0
  calendar_widget: ^0.1.0
  firebase_messaging: ^5.0.2
  flare_flutter: ^1.5.2
  animated_text_kit: ^1.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
     - images/signin.png
     - images/signin.jpeg
     - images/mimi1.gif
     - images/mimi2.gif
     - images/mimi3.gif
     - images/mimi4.gif
     - images/mimi5.gif
     - images/mimi6.gif
     - images/mimi7.gif
     - images/mimi8.gif
     - images/mimi9.gif
     - images/cat.png
     - images/logo.png
     - images/minion.flr
     - images/bear.flr

  fonts:
    - family: MyFlutterApp
      fonts:
        - asset: fonts/MyFlutterApp.ttf

