/// Flutter icons MyFlutterApp
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
/// * MFG Labs, Copyright (C) 2012 by Daniel Bruce
///         Author:    MFG Labs
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.mfglabs.com/
///
import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'MyFlutterApp';

  static const IconData submenu_about = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData submenu_achievements = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData ico_submenu_merch = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData submenu_premium = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData submenu_settings = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData submenu_share = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData but_headphones_blue = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData but_headphones_cyan = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData but_headphones_orange = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData but_headphones_purple = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData bg_goat_grey = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData fire = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData fire_1 = const IconData(0xf525, fontFamily: _kFontFam);
}
